### ISSUE TITLE
Separate completion plugin?

### ISSUE THREAD

**Issue by cprn** [calviken/vim-gdscript3#1]
You seem to be working on a completion version of this plugin. Could this be done as a separate plugin that talks with [Deoplete](https://github.com/Shougo/deoplete.nvim) instead? It's an asnychronous completion engine that works with Neovim, the most popular currently AFAIK. There are several plugins that already do that, for c/c++/c#, several kinds of javascript, php, many shell scripts, python and more. To install with `vim-plug`:

```viml
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1 
```

**Comment by calviken** [comment]
It can be made compatible with Deoplete just by adding a few lines:

```
let g:deoplete#sources = {}
let g:deoplete#sources.gdscript3 = ['omni']
let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.gdscript3 = ['\.|\w+']
```

It's also easy to adapt this to any other completion framework that supports omni completion. I plan on doing this for several popular frameworks so they work out of the box.

**Comment by cprn** [comment]
> I plan on doing this for several popular frameworks so they work out of the box.

If I understand correctly users will be able to just install Deoplete and `vim-gdscript3` and it'll work out of the box like so:

```viml
Plug 'Shougo/deoplete.nvim',
    \| Plug 'Shougo/neoinclude.vim'
    \| Plug 'calviken/vim-gdscript3', {'for': 'gdscript3'}
```

i.e. they'll be able to threat `vim-gdscript3` as any other Deoplete plugin, therefore, this ticket makes no sense. Thank you for clarification and sorry to bother you. Cheers!

**Comment by calviken** [comment]
That's right, although there may be some features of Deoplete that can't be taken advantage of (like asynchronous completion) as a result of making this a generic plugin. 

At the very least, you still get "completion-as-you-type", which I imagine is the most appealing feature for most people. (maybe I'm wrong though)
