### ISSUE TITLE
Folding support

### ISSUE THREAD

**Issue by mjtorn** [calviken/vim-gdscript3#11]
Hi!

I tried to make folding work by mimicking Python support with things like

```vim
setlocal foldmethod=syntax

syn region  gdFold
  \ matchgroup=gdComment
  \ start='#.*{{{.*$'
  \ end='#.*}}}.*$'
  \ fold transparent

syn region  gdFunctionFold
  \ start="^\z(\s*\)\%(func\)\>"
  \ end="\ze\%(\s*\n\)\+\%(\z1\s\)\@!."
  \ fold transparent
```

I'm far from an expert, so I tried a bunch of variations from that starting point but couldn't get the thing to work.

Except for that `gdFold`, it served as a test case and it worked.

I noticed these have to be configured just before the `hi def link` lines.

Is it possible to get this to work? Folding is a super-useful feature!

Thanks!

**Comment by calviken** [comment]
#12 

Let me know if that works and I'll merge it. 

`foldmethod` isn't set automatically, so make sure to set it yourself somewhere.

**Comment by mjtorn** [comment]
I tried that commit 9233dfa1cbe790b51d518419ebf123e64a94044e and it seems to work for me!

I didn't set any special `foldmethod` and it still works, with the default `foldmethod=manual`, so that's nice too :)

Thanks!
