### ISSUE TITLE
Add to `Vim Awesome`

### ISSUE THREAD

**Issue by mike239x** [calviken/vim-gdscript3#16]
Hi, I was looking through `Vim Awesome` (that one website that collects all the cool plugins for vim from across the universe) and while searching for `godot` I only found older versions of `vim-gdscript` made by other people in there.
So I thought - it would be nice to add your plugin in there as well. The process of submitting is straight-forward, but I decided that maybe you would prefer to do it on your own as the owner of the repo (in particular the `Author` input is the one that made me decide to create this issue).
What do you think?

**Comment by rafaeldelboni** [comment]
If you going to add this on Vim Awesome, please add this active fork on it:
https://github.com/clktmr/vim-gdscript3

This repo is not being supported anymore.

**Comment by idbrii** [comment]
Someone has added [both this plugin](https://vimawesome.com/plugin/vim-gdscript3) and the [clktmr fork](https://vimawesome.com/plugin/vim-gdscript3-say-im-great) to VimAwesome.

**Comment by mike239x** [comment]
Nice.
