### ISSUE TITLE
Tag or Release?

### ISSUE THREAD

**Issue by Rubonnek** [calviken/vim-gdscript3#2]
Any chance a tag or release could be issued?

I'm packaging this for the [AUR](https://aur.archlinux.org/packages/vim-gdscript-git/), but I'd like to [package a stable version](https://aur.archlinux.org/packages/vim-gdscript/) using a tag or a release.

**Comment by calviken** [comment]
[Like this?](https://github.com/calviken/vim-gdscript3/releases/tag/v0.1)

**Comment by Rubonnek** [comment]
Yes, that's good enough. Thank you!
